Repository ShehabMohsen/get-bookd, pull requests merged in 2023-05, with the labels that each got.

#11 Book Models
  server/books/admin.py
  server/books/models.py
  server/users/admin.py
  server/users/models.py
  server/users/views.py
Labels: documentation, enhancement

#12 Book Endpoints
  server/books/models.py
  server/books/serializers.py
  server/books/urls.py
  server/books/views.py
  server/server/urls.py
  server/users/views.py
Labels: documentation, enhancement

#13 Book Entry URL Fix
  server/books/urls.py
Labels: bug

#14 Backend Endpoints
  server/books/models.py
  server/books/urls.py
  server/books/views.py
  server/users/urls.py
  server/users/views.py
Labels: enhancement

#21 Feature/profile pictures
  .gitignore
  server/books/models.py
  server/books/serializers.py
  server/books/views.py
  server/requirements.txt
  server/server/settings.py
  server/server/urls.py
  server/users/views.py
Labels: enhancement

#22 Bugfix/issue 20 bug book field
  server/books/models.py
  server/books/serializers.py
  server/books/urls.py
  server/books/views.py
Labels: bug

#26 Book Entry Bugfixes
  server/books/serializers.py
  server/books/views.py
Labels: bug

#35 Fix the delete and patch collections endpoint
  server/books/views.py
Labels: bug

#48 fix: fix favorite_book_id key error
  server/books/views.py
Labels: bug

#49 Release 1.0.0
  client/src/components/BookCard.jsx
  client/src/components/SidebarWithHeader.jsx
  client/src/components/UserProfile/ProfileBookRow.jsx
  client/src/pages/BookList.jsx
  server/books/serializers.py
  server/books/views.py
Labels: enhancement
